version: '3.7'
services:
  zuul:
    image: docker.pkg.github.com/globallogicserviceandintegration/celula9-omega/zuul-gateway:v1
    ports:
      - 8050:8050
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
        - spring.cloud.config.uri=http://config:8888
    restart: always
  shopproduct:
    image: docker.pkg.github.com/globallogicserviceandintegration/celula9-omega/shop-product:v1
    ports:
      - 9099:9099
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
        - spring.cloud.config.uri=http://config:8888
    restart: always
  customer:
    image: docker.pkg.github.com/globallogicserviceandintegration/celula9-omega/customer-shop:1.0
    ports:
      - 8080:8080
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
        - spring.cloud.config.uri=http://config:8888
    restart: always
  ecommerce:
    image: docker.pkg.github.com/globallogicserviceandintegration/celula9-omega/e-commerce:v1
    ports:
      - 8099:8099
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
        - spring.cloud.config.uri=http://config:8888
    restart: always
  order:
    image: docker.pkg.github.com/globallogicserviceandintegration/celula9-omega/order-shop:v1
    ports:
      - 9090:9090
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
        - spring.cloud.config.uri=http://config:8888
    restart: always
networks:
  default:
    external:
      name: net-bootcamp