server:
  port: 9999

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PabloCook/SpringCloudConfig
          default-label: master
          
  # Spring properties in case you use different profiles
  profiles:
    active: dev