server:
  port: 9099

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GloballogicServiceAndIntegration/celula9-omega
          default-label: 
          search-paths:          - folder
          username: 
          password: 

  # Spring properties in case you use different profiles
  profiles:
    active: dev